You can also use Serenity to run your WebDriver tests on a remote machine, such as a Selenium Grid or a remote service such as provided by http://www.saucelabs.com[SauceLabs] or https://www.browserstack.com[BrowserStack]. This allows you to run your web tests against a variety of different browsers and operating systems, and also benefit from faster test execution when running the tests in parallel.

In all cases, you tell Serenity to run tests remotely by using the Selenium Remote driver,

=== Running tests against a Selenium Grid server

https://code.google.com/p/selenium/wiki/Grid2[Selenium Grid] allows you to run tests on a number of remote machines. It is open source, and relatively easy to set up and configure.

To run your Serenity tests on a Selenium Grid, you need to provide the URL of the Selenium Hub using the `webdriver.remote.url` property. You may also want to provide more information about how and where you want to run your tests, using the following properties:
`webdriver.remote.driver`:: What driver to use remotely ('firefox','chrome','iexplorer' etc.)
`webdriver.remote.browser.version`:: What version of the remote browser to use
`webdriver.remote.os`:: What operating system the tests should be run on.

For example, if you were running a Selenium Hub locally on port 4444 (the default),

-----
mvn verify -Dwebdriver.remote.url=http://localhost:4444/wd/hub -Dwebdriver.remote.driver=chrome -Dwebdriver.remote.os=WINDOWS
-----

If you are running PhantomJS remotely, you may need to specify what port PhantomJS is to run on using the `phantomjs.webdriver` property.

-----
mvn verify -Dphantomjs.webdriver=5555 -Dwebdriver.remote.url=http://seleniumgrid:4444/wd/hub
-----

You can also pass the usual driver-specific capabilities to the remote browser

-----
mvn verify -Dwebdriver.remote.url=http://localhost:4444/wd/hub -Dwebdriver.remote.driver=chrome -Dwebdriver.remote.os=WINDOWS -Dchrome.switches="--no-sandbox,--ignore-certificate-errors,--homepage=about:blank,--no-first-run"
-----

=== Running tests on BrowserStack

The setup for running tests on BrowserStack is similar to the one for SauceLabs. The following system properties are available:

`browserstack.url`:: BrowserStack Hub URL if running the tests on BrowserStack Cloud
`browserstack.os`:: OS type (e.g. WINDOWS, OS X)
`browserstack.os_version`:: OS version (e.g. Windows: XP, 7, 8 and 8.1; OS X: Snow Leopard, Lion, Mountain Lion, Mavericks, Yosemite, El Capitan)
`browserstack.browser`:: Browser type (e.g. Firefox, Safari, IE, Chrome, Opera)
`browserstack.browser_version`:: Browser version (defaults to latest stable; check https://www.browserstack.com/list-of-browsers-and-platforms?product=automate[list of available browsers])
`browserstack.device`:: BrowserStack https://www.browserstack.com/list-of-browsers-and-platforms?product=automate[mobile device] name on which tests should be run
`browserstack.deviceOrientation`:: Set the screen orientation of BrowserStack mobile device (portrait or landscape, default: portrait)
`browserstack.project`:: Specify a name for a logical group of builds on BrowserStack
`browserstack.build`:: Specify a name for a logical group of tests on BrowserStack
`browserstack.name`:: Specify an identifier for the test run on BrowserStack
`browserstack.local`:: For Testing against https://www.browserstack.com/local-testing[internal/local] servers on BrowserStack
`browserstack.localIdentifier`:: Specify an identifier fot the local browserstack connection check https://www.browserstack.com/local-testing#multiple-connections
`browserstack.debug`::  Generates screenshots at various steps in tests on BrowserStack
`browserstack.resolution`:: Sets resolution of VM on BrowserStack
`browserstack.selenium_version`::
`browserstack.ie.noFlash`:: Disable flash on Internet Explorer on BrowserStack
`browserstack.ie.driver`:: Specify the Internet Explorer webdriver version on BrowserStack
`browserstack.ie.enablePopups`:: Enable the popup blocker in Internet Explorer on BrowserStack
