Sometimes projects have a lot of tests, and executing of them takes a lot of time. Testing can be sped up significantly by running different tests in parallel. However, this is often harder to implement than it sounds.

Some build automation tools have builtin parallel test execution, but this not so good for huge amount of tests and heavy tests. For example web tests are as a rule much slower than other types of tests, it make them good candidates for concurrent testing, in theory at least, but the implementation can be tricky. For example, although it is easy enough to configure running tests in parallel, on the other hand running several webdriver instances of Firefox/Chrome in parallel on the same display, tends to become unreliable.

The natural solution in this case is to split the web tests into smaller batches, and to run each batch on a different machine and/or on a different virtual display. When each batch has finished, the results can be retrieved and aggregated into the final test reports.

However splitting tests into batches by hand tends to be tedious and unreliable – it is easy to forget to add a new test to a batch, for example, or have unevenly-distributed batches.

Serenity lets you do this automatically, by splitting your test cases evenly into batches of a given size. In practice, you run a build job for each batch - you take same sources with all tests and configure serenity to run from current copy some amount of test by providing several parameters. After that you retrieve all tests results generated by each batch to aggregate into the final serenity test report.

=== Splitting serenity tests to batches
idea of spliting tests to batches. Exiting different strategies

==== Divide equally batch strategy
description and example of using divide tests to batches with DIVIDE_EQUALLY strategy

==== Divide by test count strategy
description and example of using divide tests to batches with DIVIDE_BY_TEST_COUNT strategy

=== Configuration parallel executing with Jenkins
This approach is easy to set up on Jenkins using a multi-configuration build. In the following screenshot, we are running a multi-configuration build to run web tests across three batches. We use a single user-defined parameter (BATCH_NUMBER) to define the batch being run, passing this parameter into the Maven build job properties we discussed above.

parallel-webtests-matrix-build.png