Serenity BDD can help you to create tests for REST services, with all advantages that Serenity BDD introduce to Web Tests and even more.

It is provided tight integration with well known https://github.com/jayway/rest-assured[Rest Assured], with some improvements and advanced reporting. All what you need is use in import instead of RestAssured - SerenityRest, and that's all!!

=== Reports created when Rest is tested

If you use in your tests SerenityRest then all your requests/response will be included in generated report, so you can easy explore body, cookies, headers, response body, url as well as validate them in RestAssured way.
Here is example of generated report for some of demo tests:

// screenshot with report of rest test


=== Writing tests with Rest Assured

All Rest Assured tests are valid tests for Serenity BDD. You can use all contractions like given-when-then or expect-when-then, initialise some query parameters, and so on.

//example

More that that you can create Steps classes in Serenity BDD way and use them as reusable components, and use all features of Serenity aggregated report.
Also Serenity BDD introduce possibility to share same RestResponse between steps to allow write Steps methods in more native way:
// example with sharing


For easy configuration and resetting rest configuration you can use RestConfigurationRule. All Configuration action described in rule will executed before test and after test will be executed reset.
//RestConfigurationRule example

=== Using split classes to initialise and configure Rest Assured

